const vtubers = [
  {
    //EN Myth
    name: "Ninomae Ina’nis",
    channelId: "UCMwGHR0BTZuLsmjY_NT5Pwg",
    group: "en",
    gen: "myth",
    retired: false,
  },
  {
    name: "Mori Calliope",
    channelId: "UCL_qhgtOy0dy1Agp8vkySQg",
    group: "en",
    gen: "myth",
    retired: false,
  },
  {
    name: "Takanashi Kiara",
    channelId: "UCHsx4Hqa-1ORjQTh9TYDhww",
    group: "en",
    gen: "myth",
    retired: false,
  },
  {
    name: "Watson Amelia",
    channelId: "UCyl1z3jo3XHR1riLFKG5UAg",
    group: "en",
    gen: "myth",
    retired: true,
  },
  {
    name: "Gawr Gura",
    channelId: "UCoSrY_IQQVpmIRZ9Xf-y93g",
    group: "en",
    gen: "myth",
    retired: true,
  },
  {
    //EN Promise
    name: "IRyS",
    channelId: "UC8rcEBzJSleTkf_-agPM20g",
    group: "en",
    gen: "promise",
    retired: false,
  },
  {
    name: "Ouro Kronii",
    channelId: "UCmbs8T6MWqUHP1tIQvSgKrg",
    group: "en",
    gen: "promise",
    retired: false,
  },
  {
    name: "Hakos Baelz",
    channelId: "UCgmPnx-EEeOrZSg5Tiw7ZRQ",
    group: "en",
    gen: "promise",
    retired: false,
  },
  {
    name: "Ceres Fauna",
    channelId: "UCO_aKKYxn4tvrqPjcTzZ6EQ",
    group: "en",
    gen: "promise",
    retired: true,
  },
  {
    name: "Nanashi Mumei",
    channelId: "UC3n5uGu18FoCy23ggWWp8tA",
    group: "en",
    gen: "promise",
    retired: true,
  },
  {
    name: "Tsukumo Sana",
    channelId: "UCsUj0dszADCGbF3gNrQEuSQ",
    group: "en",
    gen: "promise",
    retired: true,
  },
  {
    //EN Advent
    name: "Shiori Novella",
    channelId: "UCgnfPPb9JI3e9A4cXHnWbyg",
    group: "en",
    gen: "advent",
    retired: false,
  },
  {
    name: "Koseki Bijou",
    channelId: "UC9p_lqQ0FEDz327Vgf5JwqA",
    group: "en",
    gen: "advent",
    retired: false,
  },
  {
    name: "Nerissa Ravencroft",
    channelId: "UC_sFNM0z0MWm9A6WlKPuMMg",
    group: "en",
    gen: "advent",
    retired: false,
  },
  {
    name: "FUWAMOCO",
    channelId: "UCt9H_RpQzhxzlyBxFqrdHqA",
    group: "en",
    gen: "advent",
    retired: false,
  },
  {
    //EN Justice
    name: "Elizabeth Rose Bloodflame",
    channelId: "UCW5uhrG1eCBYditmhL0Ykjw",
    group: "en",
    gen: "justice",
    retired: false,
  },
  {
    name: "Gigi Murin",
    channelId: "UCDHABijvPBnJm7F-KlNME3w",
    group: "en",
    gen: "justice",
    retired: false,
  },
  {
    name: "Cecilia Immergreen",
    channelId: "UCvN5h1ShZtc7nly3pezRayg",
    group: "en",
    gen: "justice",
    retired: false,
  },
  {
    name: "Raora Panthera",
    channelId: "UCl69AEx4MdqMZH7Jtsm7Tig",
    group: "en",
    gen: "justice",
    retired: false,
  },
  {
    //JP Gen 0
    name: "Tokino Sora",
    channelId: "UCp6993wxpyDPHUpavwDFqgg",
    group: "jp",
    gen: "gen0",
    retired: false,
  },
  {
    name: "Robocosan",
    channelId: "UCDqI2jOz0weumE8s7paEk6g",
    group: "jp",
    gen: "gen0",
    retired: false,
  },
  {
    name: "AZKi",
    channelId: "UC0TXe_LYZ4scaW2XMyi5_kw",
    group: "jp",
    gen: "gen0",
    retired: false,
  },
  {
    name: "Sakura Miko",
    channelId: "UC-hM6YJuNYVAmUWxeIr9FeA",
    group: "jp",
    gen: "gen0",
    retired: false,
  },
  {
    name: "Hoshimachi Suisei",
    channelId: "UC5CwaMl1eIgY8h02uZw7u8A",
    group: "jp",
    gen: "gen0",
    retired: false,
  },
  {
    //JP Gen 1
    name: "Aki Rosenthal",
    channelId: "UCFTLzh12_nrtzqBPsTCqenA",
    group: "jp",
    gen: "gen1",
    retired: false,
  },
  {
    name: "Akai Haato",
    channelId: "UC1CfXB_kRs3C-zaeTG3oGyg",
    group: "jp",
    gen: "gen1",
    retired: false,
  },
  {
    name: "Shirakami Fubuki",
    channelId: "UCdn5BQ06XqgXoAxIhbqw5Rg",
    group: ["jp", "gamers"],
    gen: ["gen1", "gamers"],
    retired: false,
  },
  {
    name: "Natsuiro Matsuri",
    channelId: "UCQ0UDLQCjY0rmuxCDE38FGg",
    group: "jp",
    gen: "gen1",
    retired: false,
  },
  {
    name: "Yozora Mel",
    channelId: "UCD8HOxPs4Xvsm8H0ZxXGiBw",
    group: "jp",
    gen: "gen1",
    retired: true,
  },
  {
    //JP Gen 2
    name: "Nakiri Ayame",
    channelId: "UC7fk0CB07ly8oSl0aqKkqFg",
    group: "jp",
    gen: "gen2",
    retired: false,
  },
  {
    name: "Yuzuki Choco",
    channelId: "UCp3tgHXw_HI0QMk1K8qh3gQ",
    group: "jp",
    gen: "gen2",
    retired: false,
  },
  {
    name: "Oozora Subaru",
    channelId: "UCvzGlP9oQwU--Y0r9id_jnA",
    group: "jp",
    gen: "gen2",
    retired: false,
  },
  {
    name: "Minato Aqua",
    channelId: "UC1opHUrw8rvnsadT-iGp7Cg",
    group: "jp",
    gen: "gen2",
    retired: true,
  },
  {
    name: "Murasaki Shion",
    channelId: "UCXTpFs_3PqI41qX2d9tL2Rw",
    group: "jp",
    gen: "gen2",
    retired: true,
  },
  {
    //JP GAMERS
    name: "Ookami Mio",
    channelId: "UCp-5t9SrOQwXMU7iIjQfARg",
    group: ["jp", "gamers"],
    gen: "gamers",
    retired: false,
  },
  {
    name: "Nekomata Okayu",
    channelId: "UCvaTdHTWBGv3MKj3KVqJVCw",
    group: ["jp", "gamers"],
    gen: "gamers",
    retired: false,
  },
  {
    name: "Inugami Korone",
    channelId: "UChAnqc_AY5_I3Px5dig3X1Q",
    group: ["jp", "gamers"],
    gen: "gamers",
    retired: false,
  },
  {
    //JP Gen 3
    name: "Usada Pekora",
    channelId: "UC1DCedRgGHBdm81E1llLhOQ",
    group: "jp",
    gen: "gen3",
    retired: false,
  },
  {
    name: "Shiranui Flare",
    channelId: "UCvInZx9h3jC2JzsIzoOebWg",
    group: "jp",
    gen: "gen3",
    retired: false,
  },
  {
    name: "Shirogane Noel",
    channelId: "UCdyqAaZDKHXg4Ahi7VENThQ",
    group: "jp",
    gen: "gen3",
    retired: false,
  },
  {
    name: "Houshou Marine",
    channelId: "UCCzUftO8KOVkV4wQG1vkUvg",
    group: "jp",
    gen: "gen3",
    retired: false,
  },
  {
    name: "Uruha Rushia",
    channelId: "UCl_gCybOJRIgOXw6Qb4qJzQ",
    group: "jp",
    gen: "gen3",
    retired: true,
  },
  {
    //JP Gen 4
    name: "Amane Kanata",
    channelId: "UCZlDXzGoo7d44bwdNObFacg",
    group: "jp",
    gen: "gen4",
    retired: false,
  },
  {
    name: "Tsunomaki Watame",
    channelId: "UCqm3BQLlJfvkTsX_hvm0UmA",
    group: "jp",
    gen: "gen4",
    retired: false,
  },
  {
    name: "Tokoyami Towa",
    channelId: "UC1uv2Oq6kNxgATlCiez59hw",
    group: "jp",
    gen: "gen4",
    retired: false,
  },
  {
    name: "Himemori Luna",
    channelId: "UCa9Y57gfeY0Zro_noHRVrnw",
    group: "jp",
    gen: "gen4",
    retired: false,
  },
  {
    name: "Kiryu coco",
    channelId: "UCS9uQI-jC3DE0L4IpXyvr6w",
    group: "jp",
    gen: "gen4",
    retired: true,
  },
  {
    //JP Gen 5
    name: "Yukihana Lamy",
    channelId: "UCFKOVgVbGmX65RxO3EtH3iw",
    group: "jp",
    gen: "gen5",
    retired: false,
  },
  {
    name: "Momosuzu Nene",
    channelId: "UCAWSyEs_Io8MtpY3m-zqILA",
    group: "jp",
    gen: "gen5",
    retired: false,
  },
  {
    name: "Shishiro Botan",
    channelId: "UCUKD-uaobj9jiqB-VXt71mA",
    group: "jp",
    gen: "gen5",
    retired: false,
  },
  {
    name: "Omaru Polka",
    channelId: "UCK9V2B22uJYu3N7eR_BT9QA",
    group: "jp",
    gen: "gen5",
    retired: false,
  },
  {
    name: "Mano Aloe",
    channelId: "UCgZuwn-O7Szh9cAgHqJ6vjw",
    group: "jp",
    gen: "gen5",
    retired: true,
  },
  {
    //JP HoloX
    name: "La+ Darknesss",
    channelId: "UCENwRMx5Yh42zWpzURebzTw",
    group: ["jp", "holox"],
    gen: "holox",
    retired: false,
  },
  {
    name: "Takane Lui",
    channelId: "UCs9_O1tRPMQTHQ-N_L6FU2g",
    group: ["jp", "holox"],
    gen: "holox",
    retired: false,
  },
  {
    name: "Hakui Koyori",
    channelId: "UC6eWCld0KwmyHFbAqK3V-Rw",
    group: ["jp", "holox"],
    gen: "holox",
    retired: false,
  },
  {
    name: "Kazama Iroha",
    channelId: "UC_vMYWcDjmfdpH6r4TTn1MQ",
    group: ["jp", "holox"],
    gen: "holox",
    retired: false,
  },
  {
    name: "Sakamata Chloe",
    channelId: "UCIBY1ollUsauvVi4hW4cumw",
    group: ["jp", "holox"],
    gen: "holox",
    retired: true,
  },
  {
    //JP DEV_IS ReGLOSS
    name: "Hiodoshi Ao",
    channelId: "UCMGfV7TVTmHhEErVJg1oHBQ",
    group: ["jp", "dev_is", "regloss"],
    gen: "regloss",
    retired: false,
  },
  {
    name: "Otonose Kanade",
    channelId: "UCWQtYtq9EOB4-I5P-3fh8lA",
    group: ["jp", "dev_is", "regloss"],
    gen: "regloss",
    retired: false,
  },
  {
    name: "Ichijou Ririka",
    channelId: "UCtyWhCj3AqKh2dXctLkDtng",
    group: ["jp", "dev_is", "regloss"],
    gen: "regloss",
    retired: false,
  },
  {
    name: "Juufuutei Raden",
    channelId: "UCdXAk5MpyLD8594lm_OvtGQ",
    group: ["jp", "dev_is", "regloss"],
    gen: "regloss",
    retired: false,
  },
  {
    name: "Todoroki Hajime",
    channelId: "UC1iA6_NT4mtAcIII6ygrvCw",
    group: ["jp", "dev_is", "regloss"],
    gen: "regloss",
    retired: false,
  },
  {
    //JP DEV_IS FLOW_GLOW
    name: "Isaki Riona",
    channelId: "UC9LSiN9hXI55svYEBrrK-tw",
    group: ["jp", "dev_is", "flowglow"],
    gen: "flowglow",
    retired: false,
  },
  {
    name: "Koganei Niko",
    channelId: "UCuI_opAVX6qbxZY-a-AxFuQ",
    group: ["jp", "dev_is", "flowglow"],
    gen: "flowglow",
    retired: false,
  },
  {
    name: "Mizumiya Su",
    channelId: "UCjk2nKmHzgH5Xy-C5qYRd5A",
    group: ["jp", "dev_is", "flowglow"],
    gen: "flowglow",
    retired: false,
  },
  {
    name: "Rindo Chihaya",
    channelId: "UCKMWFR6lAstLa7Vbf5dH7ig",
    group: ["jp", "dev_is", "flowglow"],
    gen: "flowglow",
    retired: false,
  },
  {
    name: "Kikirara Vivi",
    channelId: "UCGzTVXqMQHa4AgJVJIVvtDQ",
    group: ["jp", "dev_is", "flowglow"],
    gen: "flowglow",
    retired: false,
  },
  {
    //ID Gen 1
    name: "Ayunda Risu",
    channelId: "UCOyYb1c43VlX9rc_lT6NKQw",
    group: "id",
    gen: "gen1",
    retired: false,
  },
  {
    name: "Moona Hoshinova",
    channelId: "UCP0BspO_AMEe3aQqqpo89Dg",
    group: "id",
    gen: "gen1",
    retired: false,
  },
  {
    name: "Airani Iofifteen",
    channelId: "UCAoy6rzhSf4ydcYjJw3WoVg",
    group: "id",
    gen: "gen1",
    retired: false,
  },
  {
    //ID Gen 2
    name: "Kureiji Ollie",
    channelId: "UCYz_5n-uDuChHtLo7My1HnQ",
    group: "id",
    gen: "gen2",
    retired: false,
  },
  {
    name: "Anya Melfissa",
    channelId: "UC727SQYUvx5pDDGQpTICNWg",
    group: "id",
    gen: "gen2",
    retired: false,
  },
  {
    name: "Pavolia Reine",
    channelId: "UChgTyjG-pdNvxxhdsXfHQ5Q",
    group: "id",
    gen: "gen2",
    retired: false,
  },
  {
    //ID Gen 3
    name: "Vestia Zeta",
    channelId: "UCTvHWSfBZgtxE4sILOaurIQ",
    group: "id",
    gen: "gen3",
    retired: false,
  },
  {
    name: "Kaela Kovalskia",
    channelId: "UCZLZ8Jjx_RN2CXloOmgTHVg",
    group: "id",
    gen: "gen3",
    retired: false,
  },
  {
    name: "Kobo Kanaeru",
    channelId: "UCjLEmnpCNeisMxy134KPwWw",
    group: "id",
    gen: "gen3",
    retired: false,
  },
];
